apiVersion: apps/v1
kind: Deployment
metadata:
  name: blogsite-service-registry
  labels:
    app: blogsite-service-registry
spec:
  replicas: 1
  selector:
    matchLabels:
      app: blogsite-service-registry
  template:
    metadata:
      labels:
        app: blogsite-service-registry
    spec:
      containers:
        - name: blogsite-service-registry
          image: piyushdubey1994/blogsite-service-registry:tagversion
          ports:
            - containerPort: 8081

---
apiVersion: v1
kind: Service
metadata:
  name: blogsite-service-registry
spec:
  type: LoadBalancer
  selector:
    app: blogsite-service-registry
  ports:
    - protocol: TCP
      port: 81
      targetPort: 8081