---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: blogsite-api-gateway-deployment-loadbalancer
  labels:
    app: blog-site-service-registry-loadbalancer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: blog-site-service-registry-loadbalancer
  template:
    metadata:
      labels:
        app: blog-site-service-registry-loadbalancer
    spec:
      containers:
        - name: blog-site-service-registry-loadbalancer
          image: piyushdubey1994/blog-site-service-registry:tagversion
          ports:
            - containerPort: 8081

---
apiVersion: v1
kind: Service
metadata:
  name: blogsite-api-gateway-service-loadbalancer
spec:
  type: LoadBalancer
  selector:
    app: blog-site-service-registry-loadbalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8081