---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: blog-site-service-registry-deployment-loadbalancer
  labels:
    app: blog-site-service-registry-app-loadbalancer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: blog-site-service-registry-app-loadbalancer
  template:
    metadata:
      labels:
        app: blog-site-service-registry-app-loadbalancer
    spec:
      containers:
        - name: blog-site-service-registry-app-loadbalancer
          image: piyushdubey1994/blogsite-service-registry
          ports:
            - containerPort: 8081

---
apiVersion: v1
kind: Service
metadata:
  name: blog-site-service-registry-service-loadbalancer
spec:
  type: LoadBalancer
  selector:
    app: blog-site-service-registry-app-loadbalancer
  ports:
    - protocol: TCP
      port: 81
      targetPort: 8081